import Head from 'next/head'
import { HomeBody } from '../components'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Address Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeBody />
    </div>
  )
}
